// Code generated by the Encore 1.50.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly agents: agents.ServiceClient
    public readonly configs: configs.ServiceClient
    public readonly phases: phases.ServiceClient
    public readonly rfis: rfis.ServiceClient
    public readonly steps: steps.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.agents = new agents.ServiceClient(base)
        this.configs = new configs.ServiceClient(base)
        this.phases = new phases.ServiceClient(base)
        this.rfis = new rfis.ServiceClient(base)
        this.steps = new steps.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { cancelRun as api_agents_cancel_run_cancelRun } from "~backend/agents/cancel-run";
import { exportRuns as api_agents_export_runs_exportRuns } from "~backend/agents/export-runs";
import { getRun as api_agents_get_run_getRun } from "~backend/agents/get-run";
import { listProjectRuns as api_agents_list_project_runs_listProjectRuns } from "~backend/agents/list-project-runs";
import { listRuns as api_agents_list_runs_listRuns } from "~backend/agents/list-runs";
import { startRun as api_agents_start_run_startRun } from "~backend/agents/start-run";
import { streamRun as api_agents_stream_streamRun } from "~backend/agents/stream";

export namespace agents {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.cancelRun = this.cancelRun.bind(this)
            this.exportRuns = this.exportRuns.bind(this)
            this.getRun = this.getRun.bind(this)
            this.listProjectRuns = this.listProjectRuns.bind(this)
            this.listRuns = this.listRuns.bind(this)
            this.startRun = this.startRun.bind(this)
            this.streamRun = this.streamRun.bind(this)
        }

        public async cancelRun(params: { runId: string }): Promise<ResponseType<typeof api_agents_cancel_run_cancelRun>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/runs/${encodeURIComponent(params.runId)}/cancel`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_cancel_run_cancelRun>
        }

        public async exportRuns(params: RequestType<typeof api_agents_export_runs_exportRuns>): Promise<ResponseType<typeof api_agents_export_runs_exportRuns>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                agentId:   params.agentId,
                from:      params.from,
                projectId: params.projectId,
                q:         params.q,
                status:    params.status,
                to:        params.to,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/runs/export`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_export_runs_exportRuns>
        }

        public async getRun(params: { runId: string }): Promise<ResponseType<typeof api_agents_get_run_getRun>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/runs/${encodeURIComponent(params.runId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_get_run_getRun>
        }

        public async listProjectRuns(params: RequestType<typeof api_agents_list_project_runs_listProjectRuns>): Promise<ResponseType<typeof api_agents_list_project_runs_listProjectRuns>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/runs`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_list_project_runs_listProjectRuns>
        }

        public async listRuns(params: RequestType<typeof api_agents_list_runs_listRuns>): Promise<ResponseType<typeof api_agents_list_runs_listRuns>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                agentId:   params.agentId,
                cursor:    params.cursor,
                from:      params.from,
                limit:     params.limit === undefined ? undefined : String(params.limit),
                projectId: params.projectId,
                q:         params.q,
                status:    params.status,
                to:        params.to,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/runs`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_list_runs_listRuns>
        }

        public async startRun(params: RequestType<typeof api_agents_start_run_startRun>): Promise<ResponseType<typeof api_agents_start_run_startRun>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                input:        params.input,
                "project_id": params["project_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/${encodeURIComponent(params.agentId)}/runs`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_start_run_startRun>
        }

        public async streamRun(params: { runId: string }): Promise<ResponseType<typeof api_agents_stream_streamRun>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/runs/${encodeURIComponent(params.runId)}/stream`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_stream_streamRun>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createAgent as api_configs_create_agent_createAgent } from "~backend/configs/create-agent";
import { createApiKey as api_configs_create_api_key_createApiKey } from "~backend/configs/create-api-key";
import { deleteAgent as api_configs_delete_agent_deleteAgent } from "~backend/configs/delete-agent";
import { deleteApiKey as api_configs_delete_api_key_deleteApiKey } from "~backend/configs/delete-api-key";
import { listAgents as api_configs_list_agents_listAgents } from "~backend/configs/list-agents";
import { listApiKeys as api_configs_list_api_keys_listApiKeys } from "~backend/configs/list-api-keys";
import { updateAgent as api_configs_update_agent_updateAgent } from "~backend/configs/update-agent";

export namespace configs {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createAgent = this.createAgent.bind(this)
            this.createApiKey = this.createApiKey.bind(this)
            this.deleteAgent = this.deleteAgent.bind(this)
            this.deleteApiKey = this.deleteApiKey.bind(this)
            this.listAgents = this.listAgents.bind(this)
            this.listApiKeys = this.listApiKeys.bind(this)
            this.updateAgent = this.updateAgent.bind(this)
        }

        public async createAgent(params: RequestType<typeof api_configs_create_agent_createAgent>): Promise<ResponseType<typeof api_configs_create_agent_createAgent>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "allowed_tools": params["allowed_tools"],
                "cost_cap_usd":  params["cost_cap_usd"],
                "max_steps":     params["max_steps"],
                model:           params.model,
                name:            params.name,
                temperature:     params.temperature,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/agents`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_create_agent_createAgent>
        }

        public async createApiKey(params: RequestType<typeof api_configs_create_api_key_createApiKey>): Promise<ResponseType<typeof api_configs_create_api_key_createApiKey>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                createdBy: params.createdBy,
                name:      params.name,
                provider:  params.provider,
                secret:    params.secret,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/api-keys`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_create_api_key_createApiKey>
        }

        public async deleteAgent(params: { orgId: string, agentId: string }): Promise<ResponseType<typeof api_configs_delete_agent_deleteAgent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/agents/${encodeURIComponent(params.agentId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_delete_agent_deleteAgent>
        }

        public async deleteApiKey(params: { orgId: string, keyId: string }): Promise<ResponseType<typeof api_configs_delete_api_key_deleteApiKey>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/api-keys/${encodeURIComponent(params.keyId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_delete_api_key_deleteApiKey>
        }

        public async listAgents(params: { orgId: string }): Promise<ResponseType<typeof api_configs_list_agents_listAgents>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/agents`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_list_agents_listAgents>
        }

        public async listApiKeys(params: { orgId: string }): Promise<ResponseType<typeof api_configs_list_api_keys_listApiKeys>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/api-keys`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_list_api_keys_listApiKeys>
        }

        public async updateAgent(params: RequestType<typeof api_configs_update_agent_updateAgent>): Promise<ResponseType<typeof api_configs_update_agent_updateAgent>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "allowed_tools": params["allowed_tools"],
                "cost_cap_usd":  params["cost_cap_usd"],
                "max_steps":     params["max_steps"],
                model:           params.model,
                name:            params.name,
                temperature:     params.temperature,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/orgs/${encodeURIComponent(params.orgId)}/agents/${encodeURIComponent(params.agentId)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_configs_update_agent_updateAgent>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createPhase as api_phases_create_phase_createPhase } from "~backend/phases/create-phase";
import { deletePhase as api_phases_delete_phase_deletePhase } from "~backend/phases/delete-phase";
import { listPhases as api_phases_list_phases_listPhases } from "~backend/phases/list-phases";
import { reorderPhases as api_phases_reorder_phases_reorderPhases } from "~backend/phases/reorder-phases";
import { updatePhase as api_phases_update_phase_updatePhase } from "~backend/phases/update-phase";

export namespace phases {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createPhase = this.createPhase.bind(this)
            this.deletePhase = this.deletePhase.bind(this)
            this.listPhases = this.listPhases.bind(this)
            this.reorderPhases = this.reorderPhases.bind(this)
            this.updatePhase = this.updatePhase.bind(this)
        }

        public async createPhase(params: RequestType<typeof api_phases_create_phase_createPhase>): Promise<ResponseType<typeof api_phases_create_phase_createPhase>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                name:        params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/phases`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_phases_create_phase_createPhase>
        }

        public async deletePhase(params: { projectId: string, phaseId: string }): Promise<ResponseType<typeof api_phases_delete_phase_deletePhase>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/phases/${encodeURIComponent(params.phaseId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_phases_delete_phase_deletePhase>
        }

        public async listPhases(params: { projectId: string }): Promise<ResponseType<typeof api_phases_list_phases_listPhases>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/phases`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_phases_list_phases_listPhases>
        }

        public async reorderPhases(params: RequestType<typeof api_phases_reorder_phases_reorderPhases>): Promise<ResponseType<typeof api_phases_reorder_phases_reorderPhases>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                order: params.order,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/phases/reorder`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_phases_reorder_phases_reorderPhases>
        }

        public async updatePhase(params: RequestType<typeof api_phases_update_phase_updatePhase>): Promise<ResponseType<typeof api_phases_update_phase_updatePhase>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description: params.description,
                name:        params.name,
                status:      params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/phases/${encodeURIComponent(params.phaseId)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_phases_update_phase_updatePhase>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { answerRFI as api_rfis_answer_rfi_answerRFI } from "~backend/rfis/answer-rfi";
import { closeRFI as api_rfis_close_rfi_closeRFI } from "~backend/rfis/close-rfi";
import { createAttachment as api_rfis_create_attachment_createAttachment } from "~backend/rfis/create-attachment";
import { createRFI as api_rfis_create_rfi_createRFI } from "~backend/rfis/create-rfi";
import { deleteAttachment as api_rfis_delete_attachment_deleteAttachment } from "~backend/rfis/delete-attachment";
import { deleteRFI as api_rfis_delete_rfi_deleteRFI } from "~backend/rfis/delete-rfi";
import { getRFI as api_rfis_get_rfi_getRFI } from "~backend/rfis/get-rfi";
import { getUploadUrl as api_rfis_get_upload_url_getUploadUrl } from "~backend/rfis/get-upload-url";
import { listAttachments as api_rfis_list_attachments_listAttachments } from "~backend/rfis/list-attachments";
import { listRFIs as api_rfis_list_rfis_listRFIs } from "~backend/rfis/list-rfis";
import { reopenRFI as api_rfis_reopen_rfi_reopenRFI } from "~backend/rfis/reopen-rfi";
import { updateRFI as api_rfis_update_rfi_updateRFI } from "~backend/rfis/update-rfi";

export namespace rfis {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.answerRFI = this.answerRFI.bind(this)
            this.closeRFI = this.closeRFI.bind(this)
            this.createAttachment = this.createAttachment.bind(this)
            this.createRFI = this.createRFI.bind(this)
            this.deleteAttachment = this.deleteAttachment.bind(this)
            this.deleteRFI = this.deleteRFI.bind(this)
            this.getRFI = this.getRFI.bind(this)
            this.getUploadUrl = this.getUploadUrl.bind(this)
            this.listAttachments = this.listAttachments.bind(this)
            this.listRFIs = this.listRFIs.bind(this)
            this.reopenRFI = this.reopenRFI.bind(this)
            this.updateRFI = this.updateRFI.bind(this)
        }

        public async answerRFI(params: RequestType<typeof api_rfis_answer_rfi_answerRFI>): Promise<ResponseType<typeof api_rfis_answer_rfi_answerRFI>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                answer:     params.answer,
                answeredBy: params.answeredBy,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/answer`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_answer_rfi_answerRFI>
        }

        public async closeRFI(params: { projectId: string, rfiId: string }): Promise<ResponseType<typeof api_rfis_close_rfi_closeRFI>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/close`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_close_rfi_closeRFI>
        }

        public async createAttachment(params: RequestType<typeof api_rfis_create_attachment_createAttachment>): Promise<ResponseType<typeof api_rfis_create_attachment_createAttachment>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                bucket:      params.bucket,
                contentType: params.contentType,
                filename:    params.filename,
                path:        params.path,
                sizeBytes:   params.sizeBytes,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/attachments`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_create_attachment_createAttachment>
        }

        public async createRFI(params: RequestType<typeof api_rfis_create_rfi_createRFI>): Promise<ResponseType<typeof api_rfis_create_rfi_createRFI>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                assignedTo: params.assignedTo,
                drawingId:  params.drawingId,
                dueDate:    params.dueDate,
                priority:   params.priority,
                question:   params.question,
                subject:    params.subject,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_create_rfi_createRFI>
        }

        public async deleteAttachment(params: { projectId: string, rfiId: string, attachmentId: string }): Promise<ResponseType<typeof api_rfis_delete_attachment_deleteAttachment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/attachments/${encodeURIComponent(params.attachmentId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_delete_attachment_deleteAttachment>
        }

        public async deleteRFI(params: { projectId: string, rfiId: string }): Promise<ResponseType<typeof api_rfis_delete_rfi_deleteRFI>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_delete_rfi_deleteRFI>
        }

        public async getRFI(params: { projectId: string, rfiId: string }): Promise<ResponseType<typeof api_rfis_get_rfi_getRFI>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_get_rfi_getRFI>
        }

        public async getUploadUrl(params: RequestType<typeof api_rfis_get_upload_url_getUploadUrl>): Promise<ResponseType<typeof api_rfis_get_upload_url_getUploadUrl>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                filename: params.filename,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/upload-url`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_get_upload_url_getUploadUrl>
        }

        public async listAttachments(params: { projectId: string, rfiId: string }): Promise<ResponseType<typeof api_rfis_list_attachments_listAttachments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/attachments`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_list_attachments_listAttachments>
        }

        public async listRFIs(params: RequestType<typeof api_rfis_list_rfis_listRFIs>): Promise<ResponseType<typeof api_rfis_list_rfis_listRFIs>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                assignedTo: params.assignedTo,
                dueFrom:    params.dueFrom,
                dueTo:      params.dueTo,
                q:          params.q,
                status:     params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_list_rfis_listRFIs>
        }

        public async reopenRFI(params: { projectId: string, rfiId: string }): Promise<ResponseType<typeof api_rfis_reopen_rfi_reopenRFI>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}/reopen`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_reopen_rfi_reopenRFI>
        }

        public async updateRFI(params: RequestType<typeof api_rfis_update_rfi_updateRFI>): Promise<ResponseType<typeof api_rfis_update_rfi_updateRFI>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                assignedTo: params.assignedTo,
                drawingId:  params.drawingId,
                dueDate:    params.dueDate,
                priority:   params.priority,
                question:   params.question,
                status:     params.status,
                subject:    params.subject,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/rfis/${encodeURIComponent(params.rfiId)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_rfis_update_rfi_updateRFI>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createStep as api_steps_create_step_createStep } from "~backend/steps/create-step";
import { deleteStep as api_steps_delete_step_deleteStep } from "~backend/steps/delete-step";
import { listSteps as api_steps_list_steps_listSteps } from "~backend/steps/list-steps";
import { toggleCheckitem as api_steps_toggle_checkitem_toggleCheckitem } from "~backend/steps/toggle-checkitem";
import { updateStep as api_steps_update_step_updateStep } from "~backend/steps/update-step";

export namespace steps {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createStep = this.createStep.bind(this)
            this.deleteStep = this.deleteStep.bind(this)
            this.listSteps = this.listSteps.bind(this)
            this.toggleCheckitem = this.toggleCheckitem.bind(this)
            this.updateStep = this.updateStep.bind(this)
        }

        public async createStep(params: RequestType<typeof api_steps_create_step_createStep>): Promise<ResponseType<typeof api_steps_create_step_createStep>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                checklist:   params.checklist,
                description: params.description,
                phaseId:     params.phaseId,
                status:      params.status,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/steps`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_steps_create_step_createStep>
        }

        public async deleteStep(params: { projectId: string, stepId: string }): Promise<ResponseType<typeof api_steps_delete_step_deleteStep>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/steps/${encodeURIComponent(params.stepId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_steps_delete_step_deleteStep>
        }

        public async listSteps(params: RequestType<typeof api_steps_list_steps_listSteps>): Promise<ResponseType<typeof api_steps_list_steps_listSteps>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                phaseId: params.phaseId,
                q:       params.q,
                status:  params.status,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/steps`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_steps_list_steps_listSteps>
        }

        public async toggleCheckitem(params: { projectId: string, stepId: string, checkitemId: string }): Promise<ResponseType<typeof api_steps_toggle_checkitem_toggleCheckitem>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/steps/${encodeURIComponent(params.stepId)}/checkitems/${encodeURIComponent(params.checkitemId)}/toggle`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_steps_toggle_checkitem_toggleCheckitem>
        }

        public async updateStep(params: RequestType<typeof api_steps_update_step_updateStep>): Promise<ResponseType<typeof api_steps_update_step_updateStep>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                assigneeId:  params.assigneeId,
                description: params.description,
                phaseId:     params.phaseId,
                priority:    params.priority,
                status:      params.status,
                title:       params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.projectId)}/steps/${encodeURIComponent(params.stepId)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_steps_update_step_updateStep>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.4)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
